lbh:
  lbh_j11_position_controller:
    type: position_controllers/JointPositionController
    joint: lbh_j11_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lbh_j12_position_controller:
    type: position_controllers/JointPositionController
    joint: lbh_j12_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lbh_j13_position_controller:
    type: position_controllers/JointPositionController
    joint: lbh_j13_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lbh_j21_position_controller:
    type: position_controllers/JointPositionController
    joint: lbh_j21_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lbh_j22_position_controller:
    type: position_controllers/JointPositionController
    joint: lbh_j22_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lbh_j23_position_controller:
    type: position_controllers/JointPositionController
    joint: lbh_j23_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lbh_j32_position_controller:
    type: position_controllers/JointPositionController
    joint: lbh_j32_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lbh_j33_position_controller:
    type: position_controllers/JointPositionController
    joint: lbh_j33_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lbh_group_position_controller:
    type: barrett_hand_controllers/BarrettHandGroupPosition
    joints:
        - lbh_j11_joint
        - lbh_j12_joint
        - lbh_j13_joint
        - lbh_j21_joint
        - lbh_j22_joint
        - lbh_j23_joint
        - lbh_j32_joint
        - lbh_j33_joint
  gazebo_ros_control:
   pid_gains:
      lbh_j11_joint: {p: 100.0, i: 0.01, d: 10.0}
      lbh_j12_joint: {p: 100.0, i: 0.01, d: 10.0}
      lbh_j13_joint: {p: 100.0, i: 0.01, d: 10.0}
      lbh_j21_joint: {p: 100.0, i: 0.01, d: 10.0}
      lbh_j22_joint: {p: 100.0, i: 0.01, d: 10.0}
      lbh_j23_joint: {p: 100.0, i: 0.01, d: 10.0}
      lbh_j32_joint: {p: 100.0, i: 0.01, d: 10.0}
      lbh_j33_joint: {p: 100.0, i: 0.01, d: 10.0}
