rbh:
  rbh_j11_position_controller:
    type: position_controllers/JointPositionController
    joint: rbh_j11_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rbh_j12_position_controller:
    type: position_controllers/JointPositionController
    joint: rbh_j12_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rbh_j13_position_controller:
    type: position_controllers/JointPositionController
    joint: rbh_j13_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rbh_j21_position_controller:
    type: position_controllers/JointPositionController
    joint: rbh_j21_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rbh_j22_position_controller:
    type: position_controllers/JointPositionController
    joint: rbh_j22_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rbh_j23_position_controller:
    type: position_controllers/JointPositionController
    joint: rbh_j23_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rbh_j32_position_controller:
    type: position_controllers/JointPositionController
    joint: rbh_j32_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rbh_j33_position_controller:
    type: position_controllers/JointPositionController
    joint: rbh_j33_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rbh_group_position_controller:
    type: barrett_hand_controllers/BarrettHandGroupPosition
    joints:
        - rbh_j11_joint
        - rbh_j12_joint
        - rbh_j13_joint
        - rbh_j21_joint
        - rbh_j22_joint
        - rbh_j23_joint
        - rbh_j32_joint
        - rbh_j33_joint
  gazebo_ros_control:
   pid_gains:
      rbh_j11_joint: {p: 100.0, i: 0.01, d: 10.0}
      rbh_j12_joint: {p: 100.0, i: 0.01, d: 10.0}
      rbh_j13_joint: {p: 100.0, i: 0.01, d: 10.0}
      rbh_j21_joint: {p: 100.0, i: 0.01, d: 10.0}
      rbh_j22_joint: {p: 100.0, i: 0.01, d: 10.0}
      rbh_j23_joint: {p: 100.0, i: 0.01, d: 10.0}
      rbh_j32_joint: {p: 100.0, i: 0.01, d: 10.0}
      rbh_j33_joint: {p: 100.0, i: 0.01, d: 10.0}
