# make the namespace match the name you use to instantiate the arm in the xacro
pantilt:
  root: pantilt_bati
  tip: pantilt_cam2
  # joints is not used, since with the robot name and urdf name conventions, the parsing is hardcoded
  # but as a general solution, joint names could be loaded as well, like controllers do
  joints: 
  - pantilt_pivot1
  - pantilt_pivot2
  - pantilt_pivot3
  - pantilt_pivot4
  

